### PR TITLE
Python 3.6 compatibility fixes

### PR DESCRIPTION
**Pull request by dokai**

### CODE REVIEW

**Comment by fschulze** [comment]
I've added a functional test now and I don't see either of the issues allegedly fixed in this PR. Could you elaborate on where you see these issues and maybe add tests?

**Comment by dokai** [comment]
Sorry about the delay. Here's a demonstration of the situation as observed on my
system (macOS 10.12.7 with Macports installed Python).

I'm using ``ncat`` and the following payload to simulate the SMTP interaction.

```sh
ncat --version
Ncat: Version 7.60 ( https://nmap.org/ncat )
```

```sh
cat payload.txt
EHLO example.com
MAIL FROM: foo@example.com
RCPT TO: bar@example.com
DATA
Content-Type: text/plain; charset="utf-8"
MIME-Version: 1.0
Content-Transfer-Encoding: quoted-printable
From: foo@example.com
Subject: =?utf-8?b?VGVzdCDDpMO2?=
Date: Tue, 07 Nov 2017 12:27:53 -0800
To: bar@example.com

Body =C3=A4=C3=B6
.
QUIT
```

The subject is "Test äö" and message body is "Body äö" encoded accordingly.

Python 3.5
----------

Running the daemon with

```sh
virtualenv-3.5 py35
cd py35

./bin/python -V
Python 3.5.4

./bin/pip install mr.hermes
env DEBUG_SMTP_OUTPUT_PATH=. ./bin/python -m smtpd -n -c mr.hermes.DebuggingServer localhost:8025
```

and sending the email with

```sh
ncat -C localhost 8025 < payload.txt                                                                                                                                                  Tue Nov  7 12:38:31 2017
220 hyperion.local Python SMTP proxy version 0.3
250-hyperion.local
250 HELP
250 OK
250 OK
354 End data with <CR><LF>.<CR><LF>
250 OK
221 Bye
```

works correctly resulting in the following output from the daemon
```
---------- MESSAGE FOLLOWS ----------
Content-Type: text/plain; charset="utf-8"
MIME-Version: 1.0
Content-Transfer-Encoding: quoted-printable
From: foo@example.com
Subject: =?utf-8?b?VGVzdCDDpMO2?=
Date: Tue, 07 Nov 2017 12:27:53 -0800
To: bar@example.com
X-Peer: ::1

Body =C3=A4=C3=B6
------------ END MESSAGE ------------
```

Python 3.6
----------
Running the daemon with

```sh
virtualenv-3.6 py36
cd py36

./bin/python -V
Python 3.6.3

./bin/pip install mr.hermes
env DEBUG_SMTP_OUTPUT_PATH=. ./bin/python -m smtpd -n -c mr.hermes.DebuggingServer localhost:8026
```

and sending the email with

```sh
ncat -C localhost 8026 < payload.txt
220 hyperion.local Python SMTP proxy version 0.3
250-hyperion.local
250-8BITMIME
250 HELP
250 OK
250 OK
354 End data with <CR><LF>.<CR><LF>
```

You can now observe the `250-8BITMIME` response not present with Python 3.5.
However, due to the new keyword parameters the daemon fails with
```sh
error: uncaptured python exception, closing channel <smtpd.SMTPChannel connected ('::1', 62954, 0, 0) at 0x10332f358> (<class 'TypeError'>:process_message() got an unexpected keyword argument 'mail_options' [/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncore.py|read|83] [/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncore.py|handle_read_event|423] [/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asynchat.py|handle_read|171] [/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/smtpd.py|found_terminator|386])
```

If I apply the change in https://github.com/fschulze/mr.hermes/pull/4/commits/e639e12acaa98684c1d9e369c08b6e46abf2d40b which allows arbitrary kwargs we can observe the second issue with the following output
```
---------- MESSAGE FOLLOWS ----------
b'Content-Type: text/plain; charset="utf-8"'
b'MIME-Version: 1.0'
b'Content-Transfer-Encoding: quoted-printable'
b'From: foo@example.com'
b'Subject: =?utf-8?b?VGVzdCDDpMO2?='
b'Date: Tue, 07 Nov 2017 12:27:53 -0800'
b'To: bar@example.com'
b'X-Peer: ::1'
b''
b'Body =C3=A4=C3=B6'
------------ END MESSAGE ------------
error: uncaptured python exception, closing channel <smtpd.SMTPChannel connected ('::1', 63810, 0, 0) at 0x10cc3f358> (<class 'TypeError'>:write() argument must be str, not bytes [/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncore.py|read|83] [/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncore.py|handle_read_event|423] [/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asynchat.py|handle_read|171] [/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/smtpd.py|found_terminator|386] [/Users/dokai/Software/Development/enquos/debugsmtp/py36/lib/python3.6/site-packages/mr/hermes/__init__.py|process_message|33])
```
which is fixed by https://github.com/fschulze/mr.hermes/pull/4/commits/d6f05b10ce7c2041155632e0828677ad53306f66 for Python 3.6. Unfortunately, while testing this I realized that this change consequently breaks it for Python 3.5 making it fail with
```
---------- MESSAGE FOLLOWS ----------
Content-Type: text/plain; charset="utf-8"
MIME-Version: 1.0
Content-Transfer-Encoding: quoted-printable
From: foo@example.com
Subject: =?utf-8?b?VGVzdCDDpMO2?=
Date: Tue, 07 Nov 2017 12:27:53 -0800
To: bar@example.com
X-Peer: ::1

Body =C3=A4=C3=B6
------------ END MESSAGE ------------
error: uncaptured python exception, closing channel <smtpd.SMTPChannel connected ('::1', 65373, 0, 0) at 0x10ade38d0> (<class 'TypeError'>:a bytes-like object is required, not 'str' [/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncore.py|read|83] [/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncore.py|handle_read_event|423] [/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asynchat.py|handle_read|171] [/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/smtpd.py|found_terminator|390] [/Users/dokai/Software/Development/enquos/debugsmtp/py35/lib/python3.5/site-packages/mr/hermes/__init__.py|process_message|33])
```
in turn. So a better fix is required to support both 3.5 and 3.6 and any other version that should be supported (2.7?).


I also noticed additional Python 3 issue when you omit the `DEBUG_SMTP_OUTPUT_PATH` environment parameter
```sh
./bin/python -m smtpd -n -c mr.hermes.DebuggingServer localhost:8025
Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/smtpd.py", line 961, in <module>
    options.size_limit, enable_SMTPUTF8=options.enable_SMTPUTF8)
  File "/Users/dokai/Software/Development/enquos/debugsmtp/py35/lib/python3.5/site-packages/mr/hermes/__init__.py", line 11, in __init__
    print >>sys.stderr, "DEBUG_SMTP_OUTPUT_PATH not set, dumping mails to stdout only."
TypeError: unsupported operand type(s) for >>: 'builtin_function_or_method' and '_io.TextIOWrapper'
```
This should be easy to fix by using the print() function instead with a `from __future__ import print_function` for Python 2.

**Comment by dokai** [comment]
I rebased against master and added a fix for the `print()` issue mentioned above.

I can work on fixing https://github.com/fschulze/mr.hermes/pull/4/commits/a28e848e538b3a48b3faf954e6b939d77fc56a24 to cover all relevant Python versions if you agree upon the analysis above and confirm the Python versions that need to be supported.

**Comment by fschulze** [comment]
Turns out, the tests didn't run properly with tox. My functional test caught all the errors after that. I cherry picked two of your fixes and did the writing fix differently, so it works in all Python versions. Can you please verify?

**Comment by dokai** [comment]
Thanks, I checked and now it appears to work on all 2.7, 3.5, and 3.6 for me.

**Comment by fschulze** [comment]
I've release 1.4.0.

**Pull request closed without merging**
